kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-deployment
  namespace: nodejs
  labels:
    app: nodejs

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      name: modejs-pod
      namespace: nginx
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-container
        image: iamkaran/node-app:latest
        ports:
        - containerPort: 8000
